In [ ]:
# %conda install openpyxl

In [ ]:
import pandas as pd
s = pd.Series([10,20,30])
print(s)

In [ ]:
s = pd.Series(100, index=['a','b','c'])
print(s)

In [ ]:
s[['a','c']]
s[:2]

In [ ]:
s.values
s.index
s.dtype
s.shape
s.size

In [ ]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c','d'])
s2 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
r = s1 + s2
r
r[r.isnull()] #불리언 인덱싱

In [ ]:
population = pd.Series({
    '인천': 2947217,
    '서울': 9720846,
    '부산': 3404423,
    '대구': 2427954,
    '대전': 1471040
})
population.sort_values(ascending=False)
population[population >= 2500000]

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)
data = np.random.randn(20)
index = np.random.randint(0,20,5)
data[index] = np.nan
s = pd.Series(data)
s.describe()

In [45]:
s1 = pd.Series(['Kim', 'Lee', 'Park'], name='name')
s2 = pd.Series([25, 30, 35], name='age')
df = pd.DataFrame({'name': s1, 'age': s2})
df

   name  age
0   Kim   25
1   Lee   30
2  Park   35

In [168]:
file_path = '20250731.csv'
df = pd.read_csv(file_path)
df.head()
df.isnull().sum()

가맹점명               40
소속 시장명(또는 상점가)      0
소재지                 0
취급품목              293
지류형 가맹 여부           0
디지털형 가맹 여부          0
등록년도                0
dtype: int64

In [ ]:
# df.isnull().sum()
# df.describe()
# df.info()
#df.columns = ['1','2','3','4','5','6','7']
df
df = df.rename(columns={'가맹점명':'이름'})
#df = df.dropna()
df.isnull().sum()
df['이름'].dtype
df.sort_index(ascending=False)

,이름,소속 시장명(또는 상점가),소재지,취급품목,지류형 가맹 여부,디지털형 가맹 여부,등록년도
150540,단양보리밥,단양구경시장(단양인정시장),충북,분식,Y,Y,2010
150539,두메하누,단양구경시장(단양인정시장),충북,한식점업,Y,Y,2010
150538,파마미용실,단양구경시장(단양인정시장),충북,일반미용업,Y,Y,2010
150537,동산닭집,단양구경시장(단양인정시장),충북,"일반한식,생닭",Y,Y,2010
150536,태성마트,단양구경시장(단양인정시장),충북,식잡,Y,Y,2010
...,...,...,...,...,...,...,...
4,뿔라헤어컷,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,미용,Y,Y,2025
3,참새 방앗간,권율 골목형상점가,경기,육전 새우전,Y,Y,2025
2,일곡열쇠철물,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,열쇠,Y,Y,2025
1,못난이 꽈배기,"일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)",광주,꽈배기 도너츠,Y,Y,2025
0,초마맨1981,권율 골목형상점가,경기,짜장면 짬뽕 탕수육,Y,Y,2025

In [169]:
df.reset_index

<bound method DataFrame.reset_index of            가맹점명                소속 시장명(또는 상점가) 소재지        취급품목 지류형 가맹 여부  \
0       초마맨1981                     권율 골목형상점가  경기  짜장면 짬뽕 탕수육         Y
1       못난이 꽈배기  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)  광주     꽈배기 도너츠         Y
2        일곡열쇠철물  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)  광주          열쇠         Y
3        참새 방앗간                     권율 골목형상점가  경기      육전 새우전         Y
4         뿔라헤어컷  일곡동(제4지역:쌍용,호반,청솔2,호반일신,청솔1)  광주          미용         Y
...         ...                           ...  ..         ...       ...
150536     태성마트                단양구경시장(단양인정시장)  충북          식잡         Y
150537     동산닭집                단양구경시장(단양인정시장)  충북     일반한식,생닭         Y
150538    파마미용실                단양구경시장(단양인정시장)  충북       일반미용업         Y
150539     두메하누                단양구경시장(단양인정시장)  충북        한식점업         Y
150540    단양보리밥                단양구경시장(단양인정시장)  충북          분식         Y

       디지털형 가맹 여부  등록년도
0               Y  2025
1               Y  2025
2               Y  2025
3               Y  2025
4               Y  2025
...           ...   ...
150536          Y  2010
150537          Y  2010
150538          Y  2010
150539          Y  2010
150540          Y  2010

[150541 rows x 7 columns]>