In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('data\messy_data.csv')
df.isnull().sum()
df.shape
df.isnull().mean()
df.isnull().any(axis=1)

In [ ]:
df.head().isnull().astype(int)

In [ ]:
#결측치 삭제
#결측치만 있는 행만 출력
df[df.isnull().any(axis=1)]
#결측치가 하나라도 있는 행을 삭제
df_drop_any = df.dropna(how='any')

# 모든 값이 NaN인 행만 삭제
df_drop_all = df.dropna(how='all')
print(len(df_drop_all) - len(df))

#특정 컬럼 기준 삭제
print(len(df.dropna(subset=['age'])))
df['age'].isnull().sum()

# thresh - 최소 N개 유효값이 있어야 보존
print(len(df.dropna(thresh=5)))

In [ ]:
# 결측치 대치
# 고정값으로 대치
df_fill_zero = df.copy()

In [36]:
import pandas as pd
import numpy as np
df = pd.read_csv('data/messy_data.csv')
df['score'].interpolate(method='polynomial', order=3)
df.head()

   id    name   age   salary  score department
0   1  user_1  56.0  59545.0  17.50        마케팅
1   2  user_2  46.0  36399.0  98.22         영업
2   3  user_3  32.0  57141.0  51.66         개발
3   4  user_4  60.0  69555.0  26.08         재무
4   5  user_5  25.0  53174.0  99.63         개발

In [37]:
na_cols = df.isna().any()[df.isna().any()].index
na_cols

for col in na_cols:
    df[col] = df[col].fillna(df[col].median())

In [38]:
df.shape

(112, 6)

In [39]:
def IQR_detect(data,column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - IQR*1.5
    upper = Q3 + IQR*1.5

    outlier_mask = (data[column] > upper) | (data[column] < lower)
    return outlier_mask , lower , upper , Q1 , Q3 , IQR

In [40]:
numeric = df.describe().columns[1:]

for c in numeric:
    outlier_mask , lower , upper , Q1 , Q3 , IQR = IQR_detect(df,c)
    print(c)
    print(outlier_mask.sum())

age
4
salary
6
score
0

In [41]:
df.isnull().sum()

id            0
name          0
age           0
salary        0
score         0
department    0
dtype: int64

In [42]:
from scipy import stats
stats.zscore(df['age'])
def detect_outlier_zscore(data,column,threshold=3):
    z_score = abs(stats.zscore(data[column].dropna()))
    return ~(z_score > threshold)

In [46]:
df.columns

Index(['id', 'name', 'age', 'salary', 'score', 'department'], dtype='object')

In [62]:
for col in numeric :
    before = len(df)
    zscore_index = detect_outlier_zscore(df,col)
    df = df[zscore_index]
    removed = before - len(df)
    print(col,removed)

age 3
salary 3
score 0

In [102]:
import pandas as pd
df = pd.read_csv('data/messy_data.csv')
df.duplicated().sum()

np.int64(12)

In [103]:
d_index = df.duplicated(keep=False)
df[d_index].sort_values(by=['id'])

     id     name   age   salary  score department
0     1   user_1  56.0  59545.0  17.50        마케팅
109   1   user_1  56.0  59545.0  17.50        마케팅
108  11  user_11  28.0  64250.0  70.04         인사
10   11  user_11  28.0  64250.0  70.04         인사
18   19  user_19  41.0  38304.0  66.90         인사
110  19  user_19  41.0  38304.0  66.90         인사
106  23  user_23  19.0  52257.0  97.37         인사
22   23  user_23  19.0  52257.0  97.37         인사
30   31  user_31  59.0  74344.0  49.39         인사
111  31  user_31  59.0  74344.0  49.39         인사
105  40  user_40  38.0  46855.0  25.05         영업
39   40  user_40  38.0  46855.0  25.05         영업
44   45  user_45  42.0  62749.0  43.44         영업
104  45  user_45  42.0  62749.0  43.44         영업
103  46  user_46  31.0  30330.0  35.01         재무
45   46  user_46  31.0  30330.0  35.01         재무
53   54  user_54  61.0  42293.0   4.36         개발
101  54  user_54  61.0  42293.0   4.36         개발
70   71  user_71  51.0  38561.0  39.47         개발
102  71  user_71  51.0  38561.0  39.47         개발
80   81  user_81  38.0  50421.0    NaN         영업
107  81  user_81  38.0  50421.0    NaN         영업
100  84  user_84   NaN  56472.0  55.28         인사
83   84  user_84   NaN  56472.0  55.28         인사

In [107]:
# id는 중복되면 안됨
id_d = df.duplicated(subset=['id'])
df[id_d]

     id     name   age   salary  score department
100  84  user_84   NaN  56472.0  55.28         인사
101  54  user_54  61.0  42293.0   4.36         개발
102  71  user_71  51.0  38561.0  39.47         개발
103  46  user_46  31.0  30330.0  35.01         재무
104  45  user_45  42.0  62749.0  43.44         영업
105  40  user_40  38.0  46855.0  25.05         영업
106  23  user_23  19.0  52257.0  97.37         인사
107  81  user_81  38.0  50421.0    NaN         영업
108  11  user_11  28.0  64250.0  70.04         인사
109   1   user_1  56.0  59545.0  17.50        마케팅
110  19  user_19  41.0  38304.0  66.90         인사
111  31  user_31  59.0  74344.0  49.39         인사